plugins {
    id 'fabric-loom' version "${loom_version}"
}

group = mod_group
version = mod_version

base {
    archivesName = 'mc-client-update-fabric'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation project(':common')
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_version', minecraft_version
    filesMatching('fabric.mod.json') {
        expand version: project.version, minecraft_version: minecraft_version
    }
}

jar {
    dependsOn ':common:classes'
    from project(':common').sourceSets.main.output
}
