plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version "${moddev_version}"
}

group = mod_group
version = mod_version

base {
    archivesName = 'mc-client-update-neoforge'
}

dependencies {
    implementation project(':common')
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
        }
    }

    mods {
        mc_client_update {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

jar {
    dependsOn ':common:classes'
    from project(':common').sourceSets.main.output
}
